### ISSUE TITLE
ManagedObjectType requires an NSManagedObjectContext property

### ISSUE THREAD

**Issue by oflannabhra** [objcio/core-data#11]
In working through the first chapter, I was building the `ManagedObjectObservable` (p. 45) to handle background changes of objects. The `ManagedObjectObservable(object: mood)` method uses the [`mood.managedObjectContext`](https://github.com/objcio/core-data/blob/master/SharedCode/ManagedObject.swift#L20) property from the `ManagedObjectType` protocol. 

However, when creating the `ManagedObjectType` protocol (p. 33), it looks like the following:
```
public protocol ManagedObjectType: class {
    static var entityName: String {get}
    static var defaultSortDescriptors: [NSSortDescriptor] {get}
}
```

The [final protocol](https://github.com/objcio/core-data/blob/master/SharedCode/ManagedObject.swift#L20) includes a reference to an NSManagedObjectContext.

Why do all `ManagedObject`s need a reference to the context they belong in? Is it only for the `MangedObjectObservable`? 

I'm sure there is an important reason for it, I just didn't see any discussion of it at the first point it was required.

Thanks!

**Comment by floriankugler** [comment]
@oflannabhra `NSManagedObject` has a `managedObjectContext` property, since each managed object is tightly coupled to one context. I'm not sure off the top of my head if the observer code is the only reason we include it in the `ManagedObjectType` protocol, but it's a common pattern to access the context via a managed object. For example, when you inject a managed object into a view controller to show its data, you can get to the object's context without injecting it separately.

**Comment by oflannabhra** [comment]
:+1: awesome, thanks @floriankugler. 

That explanation was exactly what I was looking for. And thanks for the excellent book!!!
