### ISSUE TITLE
ModelBuilder.swift Compile error in Xcode 8.1

### ISSUE THREAD

**Issue by mperovic** [objcio/core-data#29]
function transformableType

`ValueTransformer.registerTransformerWithName(transform.name, transform: t, reverseTransform: r)`

error:

> Cannot convert value of type '(A?) -> Data?' to expected argument type '(_?) -> _?'

**Comment by kinwahlai** [comment]
Xcode auto migrate feature will change NSData to Data by default. 
I think we can still use NSData in swift 3.0.

So my workaround is the following ( use NSData instead of Data in ModelBuilder.swift)
`
public struct DataTransform<A> {
    public let name: String
    public let forward: (A) -> NSData?
    public let reverse: (NSData?) -> A
    public init(name: String, forward: @escaping (A) -> NSData?, reverse: @escaping (NSData?) -> A) {
        self.name = name
        self.forward = forward
        self.reverse = reverse
    }
}
`

@floriankugler Will you guys update the core-data project to swift 3.0?

**Comment by floriankugler** [comment]
@kinwahlai Yes, we're currently working on updating the whole book for Swift 3/iOS 10. Should be done pretty soon.

**Comment by floriankugler** [comment]
We'll push an update in the next days.
