### ISSUE TITLE
Purpose of `removeAllObserverTokens` in `SyncCoordinator`?

### ISSUE THREAD

**Issue by timcamber** [objcio/core-data#9]
Hello!

I've been reading and finding very useful the book. Thanks so much for writing it! We are incorporating some aspects of it into an app we are working on. It's been very useful, and we found it pretty straight-forward to add a separate remote type.

I have a question:
In the `SyncCoordinator`, `removeAllObserverTokens()` is called in the `tearDown()` method. It seems like this is a no-op, doing nothing at all (except removing tokens from the private collection of tokens). Am I correct in this understanding? Was this simply added for potential future extensibility?

**Comment by danieleggert** [comment]
It’s there mostly for extensibility. But in a multithreaded environment it is important to use explicit `tearDown()` methods to tear down constructors. You should not rely on code inside `deinit` for this, because `deinit` will run on an arbitrary thread — the one where the last strong reference is released. Using explicit tear-down logic makes it a lot more predictable to tear down objects in multithreaded code.
